// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Trailblazers.Backend.Infrastructure.Persistence;

#nullable disable

namespace Trailblazers.Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260607090434_MakeQuestionNumberNullable")]
    partial class MakeQuestionNumberNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Trailblazers.Backend.Core.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AlocId")
                        .HasColumnType("integer")
                        .HasColumnName("aloc_id");

                    b.Property<string>("ComprehensionPassage")
                        .HasColumnType("text")
                        .HasColumnName("comprehension_passage");

                    b.Property<char>("CorrectOption")
                        .HasColumnType("character(1)")
                        .HasColumnName("correct_option");

                    b.Property<int>("ExamYear")
                        .HasColumnType("integer")
                        .HasColumnName("exam_year");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_url");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<int?>("QuestionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("question_number");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id");

                    b.HasIndex("AlocId")
                        .IsUnique()
                        .HasDatabaseName("IX_exam_questions_aloc_id");

                    b.HasIndex("ExamYear", "Subject")
                        .HasDatabaseName("IX_exam_questions_year_subject");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("Trailblazers.Backend.Core.Domain.Entities.ExamSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("student_email");

                    b.Property<int>("TargetYear")
                        .HasColumnType("integer")
                        .HasColumnName("target_year");

                    b.HasKey("Id");

                    b.HasIndex("StudentEmail")
                        .HasDatabaseName("IX_exam_sessions_student_email");

                    b.ToTable("exam_sessions", (string)null);
                });

            modelBuilder.Entity("Trailblazers.Backend.Core.Domain.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Type", "CreatedAt")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_submissions_type_created_at_desc");

                    b.ToTable("submissions", (string)null);
                });

            modelBuilder.Entity("Trailblazers.Backend.Core.Domain.Entities.ExamSession", b =>
                {
                    b.OwnsMany("Trailblazers.Backend.Core.Domain.Entities.StudentAnswer", "Answers", b1 =>
                        {
                            b1.Property<int>("id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("id"));

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid")
                                .HasColumnName("question_id");

                            b1.Property<char>("SelectedOption")
                                .HasColumnType("character(1)")
                                .HasColumnName("selected_option");

                            b1.Property<Guid>("exam_session_id")
                                .HasColumnType("uuid");

                            b1.HasKey("id");

                            b1.HasIndex("exam_session_id");

                            b1.ToTable("student_answers", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("exam_session_id");
                        });

                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
